### ISSUE TITLE
需要readme中添加 如何运行代码、复线paper中lora和本地部署训练私有lora的指南

### ISSUE THREAD

**Issue by yhyu13** [StarRing2022/ZeYangGPT-Uni#5]
RT

PS 有preprint paper吗

**Comment by StarRing2022** [comment]
Lora权值交叉融合的原因是缘于Lora并非基础模型的特征向量组件，而是一个相对独立的微调增强组件，加之均基于peft库，因而才可以互换，所以认为“LLAMA训练得到的Lora只属于LLAMA是片面的理解，Lora是属于Lora的”。我们会马上正式补充到ReadME中，关键是两个步骤：
1.运行finetune.py，即基于LLAMA-7B模型在英文或中文 alpaca数据集上，利用peft库进行微调训练，将得到的lora配置文件.json和权值文件.bin存入lora-alpaca文件夹；
2.运行generate.py，要注意的是，配置文件json不能使用LLAMA的配置，而是ChatGLM的配置文件，仓库里的lora-alpaca文件夹是可以直接使用的，这样就融入了ChatGLM-6B.
实际上，如果对finetune.py的一些配置参数，如lora_alpaca、lora_rank等调整为ChatGLM的配置文件数值，也是能够实现的

**Comment by yhyu13** [comment]
LoRA的做法是:

- 基于一个预训练语言模型(比如LLAMA-7B),使用peft库对模型进行微调,得到Lora配置文件(.json)和Lora权值(.bin文件)。
- 将得到的Lora配置文件和权值应用于另一个预训练模型(比如ChatGPT-6B),将Lora融入该模型中,以增强该模型的语义表示能力。
- 由于peft库的通用性,Lora的训练与应用可以脱离具体的预训练模型,这使得Lora的权值可以在不同模型之间互相融合,实现跨模型知识迁移的效果。

所以,LoRA的关键主要有:

- 基于peft库,可以独立训练Lora并应用于不同的预训练语言模型。
- 只需要正确配置Lora的参数,就可以在不同模型之间实现Lora的权值融合,从而增强不同模型的语义表示能力。
- Lora的训练过程中,并不局限于某一个预训练模型,Lora的权值具有一定的通用性,可以在不同domain和任务中迁移。
- Lora是一种模型微调技术,目的是在保留预训练模型大部分知识的同时,进一步增强其语义理解和生成的能力。

这样理解没有错吧。

By Claude+

**Comment by StarRing2022** [comment]
嗯嗯，是的呢，感谢您的总结！我们会引用进来，再次感谢！
